version: "3.9"
services:
    db:
        image: postgres
        volumes:
        - ./data/db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=luc
        - POSTGRES_USER=luc
        - POSTGRES_PASSWORD=luc
    web:
        build: mypython
        volumes:
        - ../web-service:/code
        environment:
        - MOUNTAIN_DB=db
        ports:
        - "8000:8000"
        depends_on:
        - db
